services:
  worker:
    image: icc-worker
    build:
      context: worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app/worker
      - ./worker/hf_cache:/models/hf_cache
    environment:
      - HF_HOME=/models/hf_cache
    env_file:
      - worker/.env