services:
  backend:
    image: icc-server
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/server
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    
  frontend:
    image: icc-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3333:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
