services:
  worker:
    image: icc-worker
    tty: true
    build:
      context: worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app/worker
    environment:
      - HF_HOME=/app/worker/hf_cache
    env_file:
      - worker/.env
    restart: on-failure